name: codegen-diff

on:
  pull_request:
    paths:
      - .github/workflows/codegen-diff.yml
      - BUILD.bazel
      - WORKSPACE
      - build.bzl
      - aten/**
      - c10/**
      - tools/**
      - torch/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/codegen-diff.yml
      - BUILD.bazel
      - WORKSPACE
      - build.bzl
      - aten/**
      - c10/**
      - tools/**
      - torch/**

jobs:
  api-compatibility-check:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      # Fetch the commit, rather than the merge.
      ref: ${{ github.event.pull_request.head.sha }}
      script: |
        echo ::group::setup Bazelisk
        curl --location --output tools/bazel \
            https://raw.githubusercontent.com/bazelbuild/bazelisk/v1.16.0/bazelisk.py
        echo ::endgroup::

        tools/bazel run //tools/codegen:diff -- \
            --base-commit=${{ github.event.pull_request.base.sha }} \
            --debug

      docker-image: python:3.11.0-slim-bullseye
      runner: linux.large
